[custom]
build_flags = 
  ${KNX_TP.build_flags}
  -D KNX_ACTIVITYCALLBACK
  -D USE_KNX_DMA_UART=0 ; or 1 // uart0 oder uart1
  -D USE_KNX_DMA_IRQ=1 ; or 1 // abhängig von bereits verwendeten irqs
  -I lib/OGM-HardwareConfig/include/
  -D OPENKNX_LOOPTIME_WARNING=100
  -D IOT_GW_USE_WEBUI
  -D WEBUI_BASE_URI_USED
  -D ParamBASE_TimezoneCustom='"CET-1CEST,M3.5.0/2:00:00,M10.5.0/3:00:00"'
;debug_build_flags =

[custom_develop]
extends = custom
build_flags =
  ${custom.build_flags}
  -D OPENKNX_HEARTBEAT
  -D OPENKNX_DEBUG
  -D OPENKNX_LOOPTIME_WARNING=100
  -I lib/OGM-HardwareConfig/include/
  -D IOT_GW_USE_WEBUI
  -D WEBUI_BASE_URI_USED
  
[env:develop_REG1_JLINK_V1]
extends = UPLOAD_JLINK, RP2040_develop, RP2040_2MB, custom_develop
upload_protocol = jlink
build_flags =
  -D OPENKNX_RTT
  -D BUFFER_SIZE_UP=10240
  -D DEVICE_REG1_DALI
   ${RP2040_develop.build_flags}
   ${custom_develop.build_flags}

[env:develop_REG1_USB_V1]
extends = RP2040_UPLOAD_USB, RP2040_develop, RP2040_16MB, custom_develop
build_flags =
  -D SERIAL_DEBUG=Serial
  -D DEVICE_REG1_DALI
   ${RP2040_develop.build_flags}
   ${custom_develop.build_flags}

[env:release_REG1_V1]
extends = RP2040_releases, custom, RP2040_UPLOAD_USB
build_flags =
  -D DEVICE_REG1_DALI
  -D SERIAL_DEBUG=Serial
   ${RP2040_releases.build_flags}
   ${custom.build_flags}


; ESP32

[env:develop_REG1_ESP_DEV2_TP]
extends = ESP32_develop, ESP32_custom_develop, custom_develop, ESP32_UPLOAD_USB
build_flags =
  ${KNX_TP.build_flags}
  ${ESP32_develop.build_flags}
  ${custom_develop.build_flags}
  -D DEVICE_REG1_LAN_TP_BASE
  -D OPENKNX_USB_EXCHANGE_IGNORE
  -D KNX_IP_LAN
  -D CONFIG_ETH_ENABLED
  -D SERIAL_DEBUG=Serial
board = esp32dev
extra_scripts =
  ${env.extra_scripts}
  lib/OFM-Network/scripts/pio/minimize.py

[env:develop_REG1_ESP_DEV_TP]
extends = ESP32_develop, ESP32_custom_develop, custom_develop, ESP32_UPLOAD_USB
build_flags =
  ${KNX_TP.build_flags}
  ${ESP32_develop.build_flags}
  ${custom_develop.build_flags}
  -D OPENKNX_USB_EXCHANGE_IGNORE
  -D KNX_IP_LAN
  -D CONFIG_ETH_ENABLED
  -D SERIAL_DEBUG=Serial
  -D DEVICE_REG1_LAN_TP_2XDALI
upload_speed = 300000
board = esp32dev
extra_scripts =
  ${env.extra_scripts}
  lib/OFM-Network/scripts/pio/minimize.py

[env:release_REG1_V1-ESP]
extends = ESP32_releases, ESP32_custom_develop, custom_develop
build_flags =
  ${KNX_TP.build_flags}
  ${ESP32_develop.build_flags}
  ${custom_develop.build_flags}
  -D OPENKNX_USB_EXCHANGE_IGNORE
  -D KNX_IP_LAN
  -D CONFIG_ETH_ENABLED
  -D SERIAL_DEBUG=Serial
  -D DEVICE_REG1_LAN_TP_2XDALI
extra_scripts =
  ${env.extra_scripts}
  ${ESP32.extra_scripts}
  lib/OFM-Network/scripts/pio/minimize.py